export const LIST_BUSES_REQUEST = 'LIST_BUSES_REQUEST'
export const LIST_BUSES_SUCCESS = 'LIST_BUSES_SUCCESS'
export const LIST_BUSES_FAIL = 'LIST_BUSES_FAIL'

export const BUS_APPOITMENT_DETAIL_REQUEST = 'BUS_APPOITMENT_DETAIL_REQUEST'
export const BUS_APPOITMENT_DETAIL_SUCCESS = 'BUS_APPOITMENT_DETAIL_SUCCESS'
export const BUS_APPOITMENT_DETAIL_FAIL = 'BUS_APPOITMENT_DETAIL_FAIL'

export const BUS_APPOITMENT_CRAETE_REQUEST = 'BUS_APPOITMENT_CREATE_REQUEST'
export const BUS_APPOITMENT_CREATE_SUCCESS = 'BUS_APPOITMENT_CREATE_SUCCESS'
export const BUS_APPOITMENT_CREATE_FAIL = 'BUS_APPOITMENT_CREATE_FAIL'
export const BUS_APPOITMENT_CREATE_RESET = 'BUS_APPOITMENT_CREATE_RESET'

export const BUS_DETAIL_REQUEST = 'BUS_DETAIL_REQUEST'
export const BUS_DETAIL_SUCCESS = 'BUS_DETAIL_SUCCESS'
export const BUS_DETAIL_FAIL = 'BUS_DETAIL_FAIL'

export const BUS_CREATE_REQUEST = 'BUS_CREATE_REQUEST'
export const BUS_CREATE_SUCCESS = 'BUS_CREATE_SUCCESS'
export const BUS_CREATE_FAIL = 'BUS_CREATE_FAIL'
export const BUS_CREATE_RESET = 'BUS_CREATE_RESET'

export const BUS_DELETE_REQUEST = 'BUS_DELETE_REQUEST'
export const BUS_DELETE_SUCCESS = 'BUS_DELETE_SUCCESS'
export const BUS_DELETE_FAIL = 'BUS_DELETE_FAIL'
export const BUS_DELETE_RESET = 'BUS_DELETE_RESET'

export const BUS_APPOITMENT_DELETE_REQUEST = 'BUS_APPOITMENT_DELETE_REQUEST'
export const BUS_APPOITMENT_DELETE_SUCCESS = 'BUS_APPOITMENT_DELETE_SUCCESS'
export const BUS_APPOITMENT_DELETE_FAIL = 'BUS_APPOITMENT_DELETE_FAIL'
export const BUS_APPOITMENT_DELETE_RESET = 'BUS_APPOITMENT_DELETE_RESET'