export const LIST_BUSES_REQUEST = 'LIST_BUSES_REQUEST'
export const LIST_BUSES_SUCCESS = 'LIST_BUSES_SUCCESS'
export const LIST_BUSES_FAIL = 'LIST_BUSES_FAIL'

export const BUS_APPOITMENT_DETAIL_REQUEST = 'BUS_APPOITMENT_DETAIL_REQUEST'
export const BUS_APPOITMENT_DETAIL_SUCCESS = 'BUS_APPOITMENT_DETAIL_SUCCESS'
export const BUS_APPOITMENT_DETAIL_FAIL = 'BUS_APPOITMENT_DETAIL_FAIL'