export const RESERVATION_CREATE_REQUEST = 'RESERVATION_CREATE_REQUEST';
export const RESERVATION_CREATE_SUCCESS = 'RESERVATION_CREATE_SUCCESS';
export const RESERVATION_CREATE_FAIL = 'RESERVATION_CREATE_FAIL';
export const RESERVATION_CREATE_RESET = 'RESERVATION_CREATE_RESET';

export const RESERVATION_DETAILS_REQUEST = 'RESERVATION_DETAILS_REQUEST';
export const RESERVATION_DETAILS_SUCCESS = 'RESERVATION_DETAILS_SUCCESS';
export const RESERVATION_DETAILS_FAIL = 'RESERVATION_DETAILS_FAIL';
export const RESERVATION_DETAILS_RESET = 'RESERVATION_DETAILS_RESET';

export const RESERVATION_LIST_DETAILS_REQUEST = 'RESERVATION_LIST_DETAILS_REQUEST';
export const RESERVATION_LIST_DETAILS_SUCCESS = 'RESERVATION_LIST_DETAILS_SUCCESS';
export const RESERVATION_LIST_DETAILS_FAIL = 'RESERVATION_LIST_DETAILS_FAIL';
export const RESERVATION_LIST_DETAILS_RESET = 'RESERVATION_LIST_DETAILS_RESET';

export const RESERVATION_APPROVAL_REQUEST = 'RESERVATION_APPROVAL_REQUEST';
export const RESERVATION_APPROVAL_SUCCESS = 'RESERVATION_APPROVAL_SUCCESS';
export const RESERVATION_APPROVAL_FAIL = 'RESERVATION_APPROVAL_FAIL';
export const RESERVATION_APPROVAL_RESET = 'RESERVATION_APPROVAL_RESET';